# Generated by Django 3.1.4 on 2021-01-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('product_id_list', models.CharField(max_length=40)),
                ('status', models.CharField(blank=True, choices=[('1', 'New'), ('2', 'Labels generated'), ('3', 'Shipped'), ('4', 'Arrived at facility'), ('5', 'Closed items returned')], default=1, max_length=40)),
                ('billing_address_line_1', models.CharField(blank=True, max_length=128)),
                ('billing_address_line_2', models.CharField(blank=True, max_length=128)),
                ('billing_suburb', models.CharField(blank=True, max_length=128)),
                ('billing_city', models.CharField(blank=True, max_length=128)),
                ('billing_postcode', models.CharField(blank=True, max_length=128)),
                ('shipping_address_line_1', models.CharField(blank=True, max_length=128)),
                ('shipping_address_line_2', models.CharField(blank=True, max_length=128)),
                ('shipping_suburb', models.CharField(blank=True, max_length=128)),
                ('shipping_city', models.CharField(blank=True, max_length=128)),
                ('shipping_postcode', models.CharField(blank=True, max_length=128)),
                ('shipping_region', models.CharField(blank=True, choices=[('REGION_1', 'Region 1'), ('REGION_2', 'Region 2')], max_length=40)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
