# Generated by Django 3.1.4 on 2021-01-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapybox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapyboxuser',
            name='billing_shipping_region',
        ),
    ]
