# Generated by Django 3.1.4 on 2021-01-11 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapybox', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-id']},
        ),
    ]
