# Generated by Django 3.1.4 on 2021-01-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapybox', '0002_auto_20210104_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapyboxtemplate',
            name='image_1',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='therapyboxtemplate',
            name='image_2',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='therapyboxtemplate',
            name='image_3',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='therapyboxtemplate',
            name='image_4',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
