# Generated by Django 3.1.4 on 2021-01-05 00:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapybox', '0002_auto_20210105_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapyboxtemplate',
            name='image_1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='therapyboxtemplate',
            name='image_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='therapyboxtemplate',
            name='image_3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Image 3'),
        ),
    ]
