# Generated by Django 3.1.4 on 2021-01-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapybox', '0003_auto_20210104_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapyboxtemplate',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='therapyboxtemplate',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='therapyboxtemplate',
            name='image_4',
        ),
        migrations.AlterField(
            model_name='therapyboxtemplate',
            name='depth',
            field=models.CharField(blank=True, help_text='Approx mm', max_length=128),
        ),
        migrations.AlterField(
            model_name='therapyboxtemplate',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='therapyboxtemplate',
            name='height',
            field=models.CharField(blank=True, help_text='Approx mm', max_length=128),
        ),
        migrations.AlterField(
            model_name='therapyboxtemplate',
            name='length',
            field=models.CharField(blank=True, help_text='Approx mm', max_length=128),
        ),
        migrations.AlterField(
            model_name='therapyboxtemplate',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='therapyboxtemplate',
            name='tags',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='therapyboxtemplate',
            name='weight',
            field=models.CharField(blank=True, help_text='Approx kg', max_length=128),
        ),
    ]
