# Generated by Django 3.1.4 on 2021-01-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapybox', '0003_auto_20210105_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapyboxtemplate',
            options={'ordering': ['-id']},
        ),
    ]
