# Generated by Django 3.1.4 on 2021-01-04 14:25

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapybox', '0004_auto_20210104_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapyboxtemplate',
            name='image_1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='therapyboxtemplate',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
